### ISSUE TITLE
incruster le numero du plan dans l'image

### ISSUE THREAD

**Issue by sabinevl** [The-Chacal/CTboxPr#2]
incruster le numero du plan dans l'image au moment de l'export

**Comment by sabinevl** [comment]
à l'identique du nom du fichier exporté (donc avec le 0 en suffixe / 0010, 0020, 0030, etc.) - si possible

**Comment by The-Chacal** [comment]
Fait grâce à un effet "Nom de l’élément" ou "Incrustation des métadonnées et du code temporel" selon la version de première.
