### ISSUE TITLE
exporter une vignette de chaque plan

### ISSUE THREAD

**Issue by sabinevl** [The-Chacal/CTboxPr#3]
exporter une vignette de chaque plan (pas forcément la première image) au format jpg
dimensions et résolution du fichier à préciser, mais il faut des fichiers légers
avec aussi le numéro du plan incrusté dans l'image, si possible

**Comment by The-Chacal** [comment]
La vignette se crée selon un preset jpeg à créer. Donc tu choisis les dimensions dans "Vidéo".

Finalement, je l'ai fais se créer à 50% du clip, de sorte que peut importe la durée, il y aura toujours une image.

J'ai pas encore mis le numéro incrusté.
