### ISSUE TITLE
adapter le script pour qu'il fonctionne avec les différentes versions de Première

### ISSUE THREAD

**Issue by sabinevl** [The-Chacal/CTboxPr#4]
le script actuel ne fonctionne qu'avec la version 2023
-> soit faire en sorte que le script fonctionne avec toutes les versions de Première (y compris celles à venir)
-> soit décliner une version du script pour Première 2024 (et éventuellement Première 2022, pour les personnes comme moi qui ont un ordi "trop vieux")

**Comment by The-Chacal** [comment]
Le problème vient du fait qu'il stocke les presets dans le dossier Adobe Media Encoder, c'est donc la version de Media Encoder qui est importante.
   Normalement c'est résolu en tous cas.
